language: node_js

node_js:
- '0.12'

before_install:
- npm install --quiet -g gulp jspm typescript tsd
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.auth YjA5MTprcnRnbWszYQ==
- jspm config registries.github.maxRepoSize 0
- jspm config registries.github.handler jspm-github

#before_script:
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
#- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &"

script:
- gulp check
- gulp compile
- gulp test:unit

sudo: false
